-- Table structure for table `journey`
CREATE TABLE IF NOT EXISTS `journey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `short_description` TEXT NOT NULL,
  `long_description` TEXT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `display_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `journey`
INSERT INTO `journey` (`id`, `year`, `title`, `short_description`, `long_description`, `image`, `display_order`, `created_at`, `updated_at`) VALUES
(1, '1985', 'Rockstar Entrepreneur\'s Journey Starts', 'Born in Coimbatore — a city where business ideas float in the air along with an entrepreneurial spirit.', 'Born in 1985 in Coimbatore, Jey Anand grew up in a city where business ideas float in the air along with an entrepreneurial spirit. Surrounded by hustle, hard work, and a little creative chaos, he didn\'t just play with toys; he built ideas. Curiosity was his default setting, and "let\'s start something" became his favourite line long before he knew it would define his life.', '/Journey/1985.jpg', 1, NOW(), NOW()),
(2, '2002', 'Academic Foundations', 'Completing schooling at Stanes High School, Coimbatore, and joining GRD School of Commerce and International Business.', 'Completing his schooling at Stanes High School, Coimbatore, Jey stepped into the world of commerce and creativity by joining GRD School of Commerce and International Business. This phase refined his understanding of global markets, structured thinking, and business fundamentals, setting the stage for ventures that would soon follow.', '/Journey/2002.jpg', 2, NOW(), NOW()),
(3, '2003', 'The Birth of Happy', 'At just 17, while still in college, Jey founded HappyLabs — a design studio born out of passion and bold ambition.', 'At just 17, while still in college, Jey founded HappyLabs, a design studio born out of passion and bold ambition. What started as a creative experiment quickly became a platform where design met strategy. This marked the beginning of his entrepreneurial journey, driven not by necessity but by vision.', 'https://images.pexels.com/photos/29152435/pexels-photo-29152435.jpeg', 3, NOW(), NOW()),
(4, '2005', 'Graduation & Growth', 'From student entrepreneur to full-time founder — onboarding clients like Pricol, Suguna, LMW, Asian Paints, MRF Racing, Decathlon & more.', 'Upon completing college, Jey transitioned from student entrepreneur to full-time founder. Armed with academic knowledge and real-world experience, he strengthened HappyLabs, blending creative thinking with structured execution and started onboarding customers like Pricol, Suguna Chicken, LMW, Roots, The Chennai Silks, Asian Paints, MRF Racing, Decathlon, etc.', '/Journey/2005.jpeg', 4, NOW(), NOW()),
(5, '2006', 'Entering Media Production', 'HappyLabs expanded into media production — visual storytelling, brand films, and content creation.', 'HappyLabs expanded into media production, venturing into visual storytelling, brand films, and content creation. Jey understood early that brands needed narratives, not just logos, and he positioned his studio to deliver exactly that.', 'https://images.pexels.com/photos/67654/pexels-photo-67654.jpeg', 5, NOW(), NOW()),
(6, '2007', 'The Evolution into Branding', 'HappyLabs evolved into a full-fledged branding and marketing agency with a deeper focus on brand identity.', 'HappyLabs evolved into a full-fledged branding and marketing agency. With a deeper focus on brand identity and strategy, Jey expanded services to help businesses build meaningful, lasting impressions in competitive markets.', 'https://images.pexels.com/photos/7661627/pexels-photo-7661627.jpeg', 6, NOW(), NOW()),
(7, '2010', 'Konzept Garments Manufacturing', 'Leveraging Tiruppur\'s textile ecosystem, Jey entered manufacturing — designing athleisure uniforms for the Indian Navy.', 'Recognising the immense potential of Tiruppur — the knitwear capital of India, located near Coimbatore, Jey founded Konzept Garment Manufacturing. Leveraging the region\'s textile ecosystem, skilled workforce, and export-driven infrastructure, he strategically entered the manufacturing sector. It was a move that blended regional advantage with entrepreneurial foresight. With Konzept, the athleisure uniforms for the Indian Navy were designed, developed and deployed.', 'https://images.pexels.com/photos/31199588/pexels-photo-31199588.jpeg', 7, NOW(), NOW()),
(8, '2012', 'Karnival Event Management', 'Diversified into experiential marketing — curated experiences from corporate events to large-scale productions.', 'Jey diversified into experiential marketing with Karnival, an event management company focused on curated experiences. From corporate events to large-scale productions, this venture showcased his ability to orchestrate creativity beyond the digital and print world.', 'https://images.pexels.com/photos/35064539/pexels-photo-35064539.jpeg', 8, NOW(), NOW()),
(9, '2014', 'Enixel Social Media', 'Built to help brands navigate the rapidly evolving digital landscape with strategy, storytelling, and engagement.', 'As digital influence surged, Jey launched Enixel, a social media company built to help brands navigate the rapidly evolving digital landscape. Strategy, storytelling, and engagement became the core pillars of this new-age communication venture.', 'https://images.pexels.com/photos/15635241/pexels-photo-15635241.jpeg', 9, NOW(), NOW()),
(10, '2015', 'Honouring the Indian Naval Academy', 'Released a prestigious coffee table book for the Indian Naval Academy, unveiled by Admiral R.K. Dhawan.', 'In 2015, Jey released a prestigious coffee table book for the Indian Naval Academy, unveiled by Admiral R.K. Dhawan, then Chief of Naval Staff. This project reflected his capability to document legacy institutions with depth, design excellence, and historical sensitivity.', '/Journey/2015.jpeg', 10, NOW(), NOW()),
(11, '2017', 'Maritime Heritage of India', 'A significant work released by Prime Minister Narendra Modi, celebrating India\'s rich naval history and maritime legacy.', 'Jey authored and published Maritime Heritage of India, a significant work released by the Prime Minister of India, Narendra Modi. The book celebrated India\'s rich naval history and maritime legacy, cementing Jey\'s reputation as a serious researcher, designer, and author.', '/Journey/2017.jpg', 11, NOW(), NOW()),
(12, '2019', 'Evolution of Indian Naval Academy', 'Published and released by the President of India, Ramnath Kovind — documenting national institutions with authenticity.', 'Continuing his literary journey, Jey published Evolution of Indian Naval Academy, released by the President of India, Ramnath Kovind. This milestone further established his standing in documenting national institutions with authenticity and grandeur.', '/Journey/2019.jpeg', 12, NOW(), NOW()),
(13, '2020', 'Just Kitchen', 'A food manufacturing company launching multiple cloud kitchen brands amidst global uncertainty.', 'Amidst global uncertainty, Jey founded Just Kitchen, a food manufacturing company that launched multiple cloud kitchen brands. By adapting to changing consumer behaviour, he entered the F&B sector with innovation, operational focus, and brand clarity.', 'https://images.pexels.com/photos/32742922/pexels-photo-32742922.jpeg', 13, NOW(), NOW()),
(14, '2024', 'Pingle Infotech Pvt Ltd', 'Stepping into the technology and hyperlocal ecosystem — merging tech, commerce, and community-driven innovation.', 'In 2024, Jey formed Pingle Infotech Pvt Ltd, stepping into the technology and hyperlocal ecosystem. This venture reflected his continuous evolution — merging tech, commerce, and community-driven innovation.', 'https://images.pexels.com/photos/7213210/pexels-photo-7213210.jpeg', 14, NOW(), NOW()),
(15, '2025', 'Zamindar Kitchen', 'Heritage-inspired culinary storytelling meets contemporary dining at Sungam, Coimbatore.', 'In 2025, Jey launched Zamindar Kitchen at Sungam, Coimbatore, bringing together heritage-inspired culinary storytelling with contemporary dining experiences. Rooted in local culture yet presented with modern branding, the restaurant represents his enduring ability to blend tradition with innovation.', '/Journey/2025.jpg', 15, NOW(), NOW()),
(16, '2026', 'Tentellect', 'A next-generation data intelligence platform built to transform complex data into meaningful business insights.', 'In 2026, Jey launched Tentellect, a modern data intelligence platform designed to help organizations collect, analyze, and visualize data with clarity. Focused on empowering smarter decisions through intelligent analytics, Tentellect combines cutting-edge technology with intuitive user experiences to simplify complex business intelligence.', '/Journey/2026_2.png', 16, NOW(), NOW()),
(17, '2026', 'Odaka', 'A modern entertainment portal connecting audiences with digital culture, media, and experiences.', 'In 2026, Jey introduced Odaka, an entertainment portal created to bring together movies, music, gaming, celebrity news, and digital culture under one platform. Designed with a seamless user experience and engaging content strategy, Odaka delivers a fresh destination for entertainment enthusiasts.', '/Journey/2026_1.png', 17, NOW(), NOW()),
(18, '2026', 'Zircle', 'A social photo sharing platform designed for creators to capture, discover, and connect through visual storytelling.', 'In 2026, Jey launched Zircle, a photo sharing platform built for creators, photographers, and communities to share moments and discover inspiring visual content. With a clean, social-first experience and modern design, Zircle encourages creativity, connection, and meaningful engagement through photography.', '/Journey/2026_3.png', 18, NOW(), NOW());
